---
- name: Config | Remove clickhouse configurations, data and logs
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  become: true
  notify: restart-clickhouse
  when: clickhouse_should_clear|bool == True

- name: Config | Check clickhouse configurations, data and logs
  file:
    dest: "{{ item }}"
    owner: clickhouse
    group: clickhouse
    state: directory
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  notify: restart-clickhouse
  become: true

- name: Config | Generate system configuration
  template:
    src: config.j2
    dest: "{{ clickhouse_path_configdir }}/config.xml"
    owner: clickhouse
    group: clickhouse
  notify: restart-clickhouse
  become: true

- name: Config | Generate users configuration
  template:
    src: users.j2
    dest: "{{ clickhouse_path_configdir }}/users.xml"
    owner: clickhouse
    group: clickhouse
  when: clickhouse_users is defined
  become: true

- name: Config | Create configuration folder
  file:
    path: "{{ clickhouse_path_configdir }}/conf.d"
    state: directory
    owner: clickhouse
    group: clickhouse
  become: true

- name: Config | Generate remote_servers configuration
  template:
    src: remote_servers.j2
    dest: "{{ clickhouse_path_configdir }}/conf.d/clickhouse_remote_servers.xml"
    owner: clickhouse
    group: clickhouse
  notify: restart-clickhouse
  become: true
  when: clickhouse_shards is defined 

- name: restart-clickhouse
  service:
    name: clickhouse-server
    state: restarted
  become: true

- meta: flush_handlers
