---
- name: Uninstall | Stop service
  service:
    name: clickhouse-server
    state: stopped
  become: true

- name: Uninstall | Package uninstallation
  apt:
    name: '{{ clickhouse_package }}'
    state: absent
    purge: yes
  with_items: "{{ clickhouse_package }}"
  become: true

- name: Uninstall | Repo uninstallation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: absent
  become: true

- name: Uninstall | Remove repo key
  apt_key:
    keyserver: "{{ clickhouse_repo_keyserver }}"
    id: "{{ clickhouse_repo_key }}"
    state: absent
  become: true

- name: Uninstall | Remove clickhouse configuration, data and logs
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  become: true